src/Entity/Agence.php
<?php

namespace App\Entity;
// adresse entity
// agence controller
use App\Controller\AgenceController;
use App\Repository\AdresseRepository;

use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
// Api Platform
use ApiPlatform\Metadata\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;


// vich uploader


#[ORM\Entity(repositoryClass: AgenceRepository::class)]
// Api Platform
#[ApiResource]



class Agence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $idLocpro = null;

    #[ORM\Column(length: 100000)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    // authorize value null

    private ?string $visuel = null;


    #[ORM\Column]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $horaires = null;

    #[ORM\Column]
    private array $type = [];

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_EN = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_NL = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_DE = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_DE = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_EN = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_NL = null;

    #[ORM\Column]
    private ?bool $active = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\OneToOne(inversedBy: 'agence', cascade: ['persist', 'remove'])]
    private ?Adresse $Adresse = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'Agence')]
    private Collection $users;

    #[ORM\Column(nullable: true)]
    private ?float $Longitude = null;

    #[ORM\Column(nullable: true)]
    private ?float $Latitude = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getIdLocpro(): ?string
    {
        return $this->idLocpro;
    }

    public function setIdLocpro(string $idLocpro): self
    {
        $this->idLocpro = $idLocpro;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVisuel(): ?string
    {
        return $this->visuel;
    }

    public function setVisuel(string $visuel): self
    {
        $this->visuel = $visuel;

        return $this;
    }



    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getHoraires(): ?string
    {
        return $this->horaires;
    }

    public function setHoraires(string $horaires): self
    {
        $this->horaires = $horaires;

        return $this;
    }

    public function getType(): array
    {
        return $this->type;
    }

    public function setType(array $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescriptionEN(): ?string
    {
        return $this->description_EN;
    }

    public function setDescriptionEN(?string $description_EN): self
    {
        $this->description_EN = $description_EN;

        return $this;
    }

    public function getDescriptionNL(): ?string
    {
        return $this->description_NL;
    }

    public function setDescriptionNL(?string $description_NL): self
    {
        $this->description_NL = $description_NL;

        return $this;
    }

    public function getDescriptionDE(): ?string
    {
        return $this->description_DE;
    }

    public function setDescriptionDE(?string $description_DE): self
    {
        $this->description_DE = $description_DE;

        return $this;
    }

    public function getNomDE(): ?string
    {
        return $this->nom_DE;
    }

    public function setNomDE(?string $nom_DE): self
    {
        $this->nom_DE = $nom_DE;

        return $this;
    }

    public function getNomEN(): ?string
    {
        return $this->nom_EN;
    }

    public function setNomEN(?string $nom_EN): self
    {
        $this->nom_EN = $nom_EN;

        return $this;
    }

    public function getNomNL(): ?string
    {
        return $this->nom_NL;
    }

    public function setNomNL(?string $nom_NL): self
    {
        $this->nom_NL = $nom_NL;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }



    public function getAdresse(): ?Adresse
    {
        return $this->Adresse;
    }

    public function setAdresse(?Adresse $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addAgence($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeAgence($this);
        }

        return $this;
    }


    // public function __toString() to return user email
    public function __toString()
    {
        return $this->email;
    }

    public function getLongitude(): ?float
    {
        return $this->Longitude;
    }

    public function setLongitude(?float $Longitude): self
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->Latitude;
    }

    public function setLatitude(?float $Latitude): self
    {
        $this->Latitude = $Latitude;

        return $this;
    }

    // api platform return adresse of agence
    public function getAdresseAgence(): ?Adresse
    {
        return $this->Adresse;
    }





}


//

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Agence;
use App\Entity\Adresse;

use App\Form\AgenceType;
use App\Form\AdresseType;
use App\Repository\AgenceRepository;
use App\Repository\AdresseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/agence')]
class AgenceController extends AbstractController
{
    #[Route('/', name: 'app_agence_index', methods: ['GET'])]
    public function index(AgenceRepository $agenceRepository): Response
    {
        return $this->render('agence/index.html.twig', [


            'agences' => $agenceRepository->findAll(),



        ]);
    }

    #[Route('/new', name: 'app_agence_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AgenceRepository $agenceRepository, AdresseRepository $adresseRepository): Response
    {
        $agence = new Agence();
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            // uploaded file
            $file = $form->get('visuel')->getData();
            // dd($file);
            // generate a unique name for the file before saving it
            $fileName = md5(uniqid()).'.'.$file->guessExtension();
            // dd($fileName);
            // move the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('kernel.project_dir').'/public/upload',
                $fileName
            );
            // updates the 'brochureFilename' property to store the PDF file name
            // instead of its contents
            $agence->setVisuel($fileName);
            // set agence active to true
            $agence->setActive(true);

            // get adresse form
            $adresse = $form->get('adresse')->getData();

            // set agence adresse
            $agence->setAdresse($adresse);



            $agenceRepository->save($agence, true);

            // send flash message
            $this->addFlash('success', 'Agence ajoutée avec succès');


            return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agence/new.html.twig', [
            'agence' => $agence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_agence_show', methods: ['GET'])]
    public function show(Agence $agence): Response
    {
        return $this->render('agence/show.html.twig', [
            'agence' => $agence,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_agence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Agence $agence, AgenceRepository $agenceRepository): Response
    {

        // get agence adresse
        $adresse = $agence->getAdresse();

        // prefilled form



        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()) {

            // check if a file already exists for this entity and upload form is empty
            if ($agence->getVisuel() && !$form->get('visuel')->getData()) {
                // set the old file name
                $agence->setVisuel($agence->getVisuel());
            } else {
                // uploaded file
                $file = $form->get('visuel')->getData();
                // dd($file);
                // generate a unique name for the file before saving it
                $fileName = md5(uniqid()).'.'.$file->guessExtension();
                // dd($fileName);
                // move the file to the directory where brochures are stored
                $file->move(
                    $this->getParameter('kernel.project_dir').'/public/upload',
                    $fileName
                );
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $agence->setVisuel($fileName);

                   // get adresse form
                $adresse = $form->get('adresse')->getData();

            // set agence adresse
                $agence->setAdresse($adresse);



            }

            $agenceRepository->save($agence, true);

               // send flash message
               $this->addFlash('warning', 'Agence modifiée avec succès');

            return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
        }


        return $this->renderForm('agence/edit.html.twig', [
            'agence' => $agence,
            'form' => $form,
            //'visuel' => $agence->getVisuel(),

        ]);

    }

    #[Route('/{id}', name: 'app_agence_delete', methods: ['POST'])]
    public function delete(Request $request, Agence $agence, AgenceRepository $agenceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agence->getId(), $request->request->get('_token'))) {
            $agenceRepository->remove($agence, true);
        }

        // send flash message
        $this->addFlash('danger', 'Agence supprimée avec succès');

        return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
    }


    // route to set active or inactive post method
    #[Route('/{id}/active', name: 'app_agence_active', methods: ['POST'])]
    public function active(Agence $agence, AgenceRepository $agenceRepository): Response
    {
        $agence->setActive(!$agence->isActive());
        $agenceRepository->save($agence, true);

            // send flash message
            $this->addFlash('warning', 'Statut de l\'agence modifié avec succès');

        return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
    }

    // app_agence_search route post method
    #[Route('/search', name: 'app_agence_search', methods: ['POST'])]
    public function search(Request $request, AgenceRepository $agenceRepository): Response
    {
        $search = $request->request->get('search');
        // findByName
        $agences = $agenceRepository->findByName($search);




        return $this->render('agence/index.html.twig', [
            'agences' => $agences,
        ]);
    }


    //  api platform route return adresse of agence
    #[Route('/{id}/adresse', name: 'app_agence_adresse', methods: ['GET'])]
    public function adresse(Agence $agence): Response
    {
        $adresse = $agence->getAdresse();

        return $this->json($adresse, 200, [], ['groups' => 'adresse:read']);

    }









}

templates/agence/_delete_form.html.twig
<form method="post" action="{{ path('app_agence_delete', {'id': agence.id}) }}" onsubmit="return confirm('Poursuivre la suppression du contenu ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agence.id) }}">
    <button class="btn btn-danger btnDel"><i class="fa fa-trash"></i> </button>
</form>

templates/agence/_form.html.twig
{# modal filemanager #}





{{ form_start(form) }}
<br/>

<div class="row">

<div class="col-3">
<label/>Responsable de l'Agence</label>
{{ form_row(form.user) }}
<br/>
</div>
<div class="col-6">
<br/>
{# button add user  #}
<button type="button" id="userAdd" class="btn btn-primary">
  <i class="fa fa-user"></i> Ajouter un utilisateur
</button>
<br/>
</div>

</div>



<div class="row">

<div class="col-3">

{{ form_row(form.nom) }}





</div>

<div class="col-3">
{{ form_row(form.nom_EN) }}

</div>

<div class="col-3">
{{ form_row(form.nom_DE) }}

</div>

<div class="col-3">
{{ form_row(form.nom_NL) }}

</div>



<div class="col-4">

{{ form_row(form.idLocpro) }}


</div>

<div class="col-4">

{{ form_row(form.type) }}


</div>

<div class="col-4">

{{ form_row(form.email) }}


</div>


<div class="col-12">
<br/>
<label>Description</label>
<br/>
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Description Française
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">

     {{ form_row(form.description) }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
       Description Anglaise
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
       {{ form_row(form.description_EN) }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Description Allemande
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        {{ form_row(form.description_DE) }}

      </div>
    </div>
  </div>
    <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Description Néerlandaise
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        {{ form_row(form.description_NL) }}

      </div>
    </div>
  </div>
</div>
<br/>

<div class="col-12">

{{ form_row(form.visuel) }}

    <div class="row">
        <div class="col-xs-6 col-md-3">
            <img src="" class="img-responsive" id="image" alt="">
        </div>
    </div>



{# button to open filemanager #}
<form>
    <div class="form-group">
        <div class="col-sm-10">
            {# <input class="form-control" id="path" type="text"> #}

        </div>
        <div class="col-sm-2">
            <button id="mLaunch" type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
                <span class="glyphicon glyphicon-folder-open">MEDIA</span>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-md-3">
            <img src="" class="img-responsive" id="image" alt="">
        </div>
    </div>
</form>


<br/>
</div>

<div class="row">

<div class="col-3">


{# {{ form_row(form.localisation) }} #}

{{ form_row(form.longitude) }}



</div>

<div class="col-3">


{# {{ form_row(form.localisation) }} #}

{{ form_row(form.latitude) }}



</div>




<div class="col-3">


{{ form_row(form.horaires) }}

</div>
<div class="col-3">


{{ form_row(form.telephone) }}

</div>


{# adresse input #}
<div class="col-12">
<br/>
{{ form_row(form.adresse) }}
</div>

{# ville input #}




</div>
    <button class="btn btn-sm btn-success mt-2">{{ button_label|default('Valider') }}</button>
{# {{ form_end(form) }} #}
{{ form_end(form) }}

 <!-- Modal -->
    <div class="modal  fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">
                    <iframe id="myframe" src="{{ path('app_media') }}" width="100%" height="500"
                            frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>


<script>
    $(document).ready(function () {



    // btn userAdd click
    $('#userAdd').click(function () {

       location.href = "{{ path('app_user_new') }}";

    });








// detect if modal is closed
        $('#myModal').on('hidden.bs.modal', function () {

          // get value of localstorage
            var path = localStorage.getItem('url');

            path = 'http://127.0.0.1:8000'+path

            // set value of path to input
            $('#path').val(path);

            // set value of path to image

                // Get a reference to our file input
    const fileInput = document.querySelector('input[type="file"]');

    // Create a new File object
    const myFile = new File(['Hello World!'], path, {
        //type image png jpg
        type: 'image/png',


        lastModified: new Date(),
    });



    // Now let's create a DataTransfer to get a FileList
    const dataTransfer = new DataTransfer();
    dataTransfer.items.add(myFile);
    fileInput.files = dataTransfer.files;



        });



    });
</script>

templates/agence/edit.html.twig
{% extends 'page.html.twig' %}

{% block title %}Edit Agence{% endblock %}

{% block body %}
<div class="container  mt-4 p-4">
    <h4>Edition de l'Agence</h4>
    {# {{agence.visuel}} #}
    {# btn back #}
    <a href="{{ path('app_agence_index') }}" class="btn btn-primary btn-sm mb-2">Retour</a>
        {{ include('agence/_delete_form.html.twig') }}
    {# form #}

           {# btn post method to set active or not #}
    <form method="post" action="{{ path('app_agence_active', {'id': agence.id}) }}" style="display: inline-block">
        <input type="hidden" name="_method" value="POST">
        <input type="hidden" name="_token" value="{{ csrf_token('active' ~ agence.id) }}">
        {% if agence.active == 1 %}
            <button class="btn btn-success btn-sm mb-2" type="submit">Activer</button>
        {% else %}
            <button class="btn btn-danger btn-sm mb-2" type="submit">Désactiver</button>
        {% endif %}
    </form>


    {{ include('agence/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    {# btn delete #}


</div>
<script>


document.addEventListener("DOMContentLoaded", function(event) {



let fileUploaded = "/upload/{{agence.visuel}}";





var input = document.querySelector('input[type="file"]');


// set value of input file with current image
//input.value = fileUploaded;





// prefill input file with current image


if (fileUploaded !== "/upload/") {
    // create thumbnail of current image
    var img = document.createElement("img");
    img.src = fileUploaded;
    img.width = 100;
    img.height = 100;
    img.style.margin = "10px";
    img.style.border = "1px solid #ccc";
    img.style.borderRadius = "5px";
    img.style.display = "inline-block";
    img.style.verticalAlign = "middle";
    img.style.objectFit = "cover";
    img.style.objectPosition = "center";

    // append thumbnail to div before input file
    input.parentNode.insertBefore(img, input);



}



});



</script>
{% endblock %}

templates/agence/index.html.twig
{% extends 'page.html.twig' %}

{% block title %}Agence index{% endblock %}

{% block body %}
<div>
    <h1 style="font-weight:300">GESTION DES AGENCES</h1>

    {# flash message #}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('danger') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('info') %}
        <div class="alert alert-info">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('primary') %}
        <div class="alert alert-primary">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('secondary') %}
        <div class="alert alert-secondary">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('light') %}
        <div class="alert alert-light">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('dark') %}
        <div class="alert alert-dark">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('link') %}
        <div class="alert alert-link">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('white') %}
        <div class="alert alert-white">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('black') %}
        <div class="alert alert-black">
            {{ message }}
        </div>
    {% endfor %}

    {# flash message #}
    {% for message in app.flashes('muted') %}
        <div class="alert alert-muted">
            {{ message }}
        </div>
    {% endfor %}






    {# div container #}

    <div class="container-fluid mt-5">
        <div class="row" id="list">



        <div class="col-6 mb-4">
        <a class="btn btn-sm btn-success pull-right" href="{{ path('app_agence_new') }}"><i class="fa fa-plus"></i> Ajouter</a>
        </div>

             <div class="col-6 mb-4">
       {# input search #}
        <form action="{{ path('app_agence_search') }}" method="get">
            <div class="input-group mb-3">
                <input type="text" id="searchTerm" class="form-control searchTerm" placeholder="Rechercher une Agence (Nom, ville...)" name="search" value="">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
            </div>
        </form>
        </div>




         {% for agence in agences %}
            <div class="col-md-6 col-lg-3 col-sm-6 col-xs-6 {{ agence.nom }} mb-4 filtered">
                <div class="card card-flush h-xl-100 ribbon ribbon-top ribbon-vertical">

                  {% if agence.active == 0 %}
                                                                                  <div class="ribbon-label bg-success">ACTIVE</div>
                                                                    {% else %}
                                                                                <div class="ribbon-label bg-danger">INACTIVE</div>
                                                                    {% endif %}


												<!--begin::Body-->
												<div class="card-body text-center pb-5">


													<!--begin::Overlay-->
													<a class="d-block overlay" data-fslightbox="lightbox-hot-sales" href="{{ asset('upload/' ~ agence.visuel) }}">
														<!--begin::Image-->

                                                                   {% if agence.visuel %}

                                            <div class="overlay-wrapper bgi-no-repeat bgi-position-center bgi-size-cover card-rounded mb-7" style="height: 266px;background-image:url('{{ asset('upload/' ~ agence.visuel) }}')"></div>

                                                                    {% else %}
                                                                        Aucun visuel
                                                                    {% endif %}


                                                        <!--end::Image-->
														<!--begin::Action-->
														<div class="overlay-layer card-rounded bg-dark bg-opacity-25">
															<i class="bi bi-eye-fill fs-2x text-white"></i>
														</div>
														<!--end::Action-->
													</a>
													<!--end::Overlay-->
													<!--begin::Info-->
													<div class="d-flex align-items-end flex-stack mb-1">
														<!--begin::Title-->
														<div class="text-start">
															<span class="fw-bold text-gray-800 cursor-pointer text-hover-primary fs-4 d-block">{{ agence.nom }}</span>
															{# <span class="text-gray-400 mt-1 fw-bold fs-6">{{ agence.description|striptags|slice(0, 50) }}</span> #}
                                                            {# descripttion html format #}


														</div>
														<!--end::Title-->
														<!--begin::Total-->

														<!--end::Total-->
													</div>
													<!--end::Info-->
												</div>
												<!--end::Body-->
												<!--begin::Footer-->
												<div class="card-footer d-flex flex-stack pt-0">
													<!--begin::Link-->
													<a class="btn btn-sm btn-primary flex-shrink-0 me-2" href="{{ path('app_agence_show', {'id': agence.id}) }}" ><i class="fa fa-eye"></i> Consulter</a>
													<a class="btn btn-sm btn-danger flex-shrink-0 me-2" href="{{ path('app_agence_edit', {'id': agence.id}) }}" ><i class="fa fa-pen"></i> Modifier</a>

                                                    <!--end::Link-->
													<!--begin::Link-->

													<!--end::Link-->
												</div>
												<!--end::Footer-->
											</div>
            </div>
        {% else %}
            <tr>
                <td colspan="9">Aucune agence :(</td>
            </tr>
        {% endfor %}



    </div>




    </div>
</div>
<script>
{# filter div based on input value #}
var input = document.getElementById("searchTerm");
input.addEventListener("input", myFunction);

function myFunction(e) {

    var filter = e.target.value.toUpperCase();
    var list = document.getElementById("list");
    var items = list.getElementsByClassName("filtered");

    for (var i = 0; i < items.length; i++) {
        var item = items[i];
        var text = item.getElementsByClassName("card-body text-center pb-5")[0].innerText.toUpperCase();
        if (text.indexOf(filter) > -1) {
            item.style.display = "";
        } else {
            item.style.display = "none";
        }
    }

}
</script>
{% endblock %}

templates/agence/new.html.twig
{% extends 'page.html.twig' %}

{% block title %}New Agence{% endblock %}

{% block body %}
<div class="container  mt-4 p-4">
    <h4>Créer une Agence</h4>
        <a class="btn btn-secondary btn-sm" href="{{ path('app_agence_index') }}">Retour</a>
<div class="row g-3 align-items-center">
<div class="col-12">

    {# modale #filemanager #}
     <!-- Modal -->


    {{ include('agence/_form.html.twig') }}







</div>
</div>

</div>
{% endblock %}